#!/bin/bash
# Install as /usr/bin/VBoxManageWrapper

VBOX_CMD=/usr/bin/VBoxManage
LOG_FILE=/var/log/VBoxManageWrapper.log

#
loop=0
max_loop=5

echo "Received ($(date +%Y%m%d%H%M)): ${VBOX_CMD} $@ " >> ${LOG_FILE}

case $1 in
	'startvm'|'controlvm')
		VARGS="$@ --type headless"
		;;
	'modifyvm')
		VM_NAME=$2
		/usr/bin/VBoxManageWrapper controlvm ${VM_NAME} poweroff
		VARGS="$@"
		;;
	*)
		VARGS="$@"
		;;
esac


while [ $loop -lt $max_loop ];
do
	echo "Executing ($(date +%Y%m%d%H%M)): ${VBOX_CMD} ${VARGS} " >> ${LOG_FILE}
	${VBOX_CMD} ${VARGS}
	RET=$?
	echo "Got rc=${RET} ($(date +%Y%m%d%H%M)) from: ${VBOX_CMD} ${VARGS}" >> ${LOG_FILE}
	if [ $RET -eq 0 ]; then
		break
	else
		loop=$((loop + 1))
		echo "Retrying ${loop}/${max_loop} ($(date +%Y%m%d%H%M))..." >> ${LOG_FILE}
		sleep 1
	fi
done
